import { useState, useEffect } from 'react';
import { useHealthMockData } from '../hooks/useHealthMockData';

import Header from '../components/Header';
import PatientProfile from '../components/PatientProfile';
import VideoFeed from '../components/VideoFeed';
import VitalGrid from '../components/VitalGrid';
import ChartsSection from '../components/ChartsSection';
import BottomPanels from '../components/BottomPanels';
import StatusBar from '../components/StatusBar';

export default function Dashboard() {
  const {
    bpm, respiratory, bodyTemp, weight, hrChange, graphData, weightGraphData
  } = useHealthMockData();

  // We hardcode SpO2, CO2, Humidity since they aren't generated by the hook but exist in the image
  const spO2 = 97;
  const co2 = 39;
  const humidity = 50;

  const [alerts, setAlerts] = useState([
    { id: '1', title: 'Stable', message: 'All parameters are within normal range.', time: '10:24 AM', type: 'success' },
    { id: '2', title: 'Watch', message: 'Slight increase in heart rate trend.', time: '10:20 AM', type: 'warning' },
    { id: '3', title: 'O₂ Low Risk', message: 'Oxygen level approaching lower threshold.', time: '10:18 AM', type: 'info' }
  ]);
  const [anomalies, setAnomalies] = useState({
    bpm: false,
    respiratory: false,
    bodyTemp: false,
    spO2: false,
    co2: false
  });

  const [envStatus, setEnvStatus] = useState({
    oxygen: 21.0,
    co2: 38,
    airflow: 25,
    isAdjustingO2: false,
    isFlushingCO2: false
  });

  const [aiInterventions, setAiInterventions] = useState({
    monitoring: 'Active',
    digitalTwin: 'Active',
    predictive: 'Active',
    closedLoop: 'Active',
    isActive: false
  });

  useEffect(() => {
    const newAnomalies = {
      bpm: bpm > 145 || bpm < 95,
      respiratory: respiratory > 35 || respiratory < 18,
      bodyTemp: bodyTemp > 102.5 || bodyTemp < 100.0,
      spO2: spO2 < 95,
      co2: co2 > 43 || co2 < 32
    };
    
    setAnomalies(newAnomalies);

    setEnvStatus(prev => {
      let newOxygen = prev.oxygen;
      let newAirflow = prev.airflow;
      let newCo2 = prev.co2;
      let adjustingO2 = false;
      let flushingCO2 = false;
      
      if (newAnomalies.spO2 || newAnomalies.bpm) {
        newOxygen = Math.min(prev.oxygen + 0.5, 40.0);
        newAirflow = Math.min(prev.airflow + 2, 45);
        adjustingO2 = true;
      } else if (prev.oxygen > 21.0) {
        newOxygen = Math.max(prev.oxygen - 0.2, 21.0);
        if (newOxygen === 21.0 && !newAnomalies.co2 && !newAnomalies.respiratory) newAirflow = Math.max(prev.airflow - 1, 25);
      }

      if (newAnomalies.co2 || newAnomalies.respiratory) {
        newAirflow = Math.min(newAirflow + 5, 50);
        newCo2 = Math.max(prev.co2 - 1, 35);
        flushingCO2 = true;
      } else if (prev.co2 < 38) {
        newCo2 = Math.min(prev.co2 + 0.2, 38);
        if (!newAnomalies.spO2 && !newAnomalies.bpm) newAirflow = Math.max(prev.airflow - 1, 25);
      }

      return {
        oxygen: Number(newOxygen.toFixed(1)),
        co2: Number(newCo2.toFixed(1)),
        airflow: newAirflow,
        isAdjustingO2: adjustingO2,
        isFlushingCO2: flushingCO2
      };
    });

    setAiInterventions(prev => {
      let closedLoopMsg = 'Active';
      let isActive = false;
      
      if (newAnomalies.spO2 || newAnomalies.bpm) {
        closedLoopMsg = 'Adjusting O₂...';
        isActive = true;
      } else if (newAnomalies.co2 || newAnomalies.respiratory) {
        closedLoopMsg = 'Flushing CO₂...';
        isActive = true;
      }

      return {
        ...prev,
        closedLoop: closedLoopMsg,
        isActive: isActive
      };
    });

    const now = new Date();
    const timeStr = now.toLocaleTimeString('en-US', { hour: '2-digit', minute: '2-digit' });
    
    const newAlerts = [];
    if (newAnomalies.bpm) newAlerts.push({ id: `bpm-${now.getTime()}`, title: 'Watch', message: 'Abnormal heart rate detected.', time: timeStr, type: 'warning' });
    if (newAnomalies.respiratory) newAlerts.push({ id: `resp-${now.getTime()}`, title: 'Watch', message: 'Respiratory rate is abnormal.', time: timeStr, type: 'warning' });
    if (newAnomalies.bodyTemp) newAlerts.push({ id: `temp-${now.getTime()}`, title: 'Watch', message: 'Temperature out of range.', time: timeStr, type: 'warning' });
    if (newAnomalies.spO2) newAlerts.push({ id: `spo2-${now.getTime()}`, title: 'O₂ Low Risk', message: 'Oxygen level approaching lower threshold.', time: timeStr, type: 'info' });
    if (newAnomalies.co2) newAlerts.push({ id: `co2-${now.getTime()}`, title: 'Watch', message: 'CO₂ level is abnormal.', time: timeStr, type: 'warning' });
    
    if (newAlerts.length > 0) {
      setAlerts(prev => {
        const combined = [...newAlerts, ...prev];
        const unique = combined.filter((alert, index, self) => 
          index === self.findIndex((a) => a.message === alert.message && a.time === alert.time)
        );
        return unique.slice(0, 50); // Keep up to 50 alerts for history
      });
    }
  }, [bpm, respiratory, bodyTemp, spO2, co2]);

  return (
    <div className="min-h-screen bg-[#111319] flex flex-col font-sans overflow-hidden">
      
      <Header />

      <main className="flex-1 p-5 flex flex-col gap-5 overflow-y-auto">
        
        {/* Top Section: 3 columns */}
        {/* Looking at the image, Patient Profile is about 25%, Video is about 40%, Vitals are about 35% */}
        <div className="flex flex-col lg:flex-row gap-5 h-auto lg:h-[280px]">
          <div className="w-full lg:w-[300px] shrink-0">
            <PatientProfile />
          </div>
          
          {/* Locked size for VideoFeed */}
          <div className="w-full lg:w-[360px] shrink-0">
            <VideoFeed />
          </div>
          
          {/* VitalGrid takes the remaining space */}
          <div className="flex-1 min-w-0">
            <VitalGrid 
              bpm={bpm} 
              respiratory={respiratory} 
              bodyTemp={bodyTemp} 
              weight={weight} 
              hrChange={hrChange}
              co2={co2}
              humidity={humidity}
              spO2={spO2}
              anomalies={anomalies}
            />
          </div>
        </div>

        {/* Middle Section: Charts */}
        <ChartsSection graphData={graphData} weightGraphData={weightGraphData} bpm={bpm} respiratory={respiratory} weight={weight} />

        {/* Bottom Section: Environment, Alerts, Intelligence */}
        <BottomPanels alerts={alerts} envStatus={envStatus} aiInterventions={aiInterventions} />

      </main>

      {/* Very Bottom: Status/Signal Bar */}
      <StatusBar />
    </div>
  );
}
